# Generated by Django 3.2.5 on 2021-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20211017_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Gps',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
